version: "3.9"
services:
  web-app:
    build: web-app
    container_name: web-app
    build:
      context: ./web-app
    ports:
      - "8080:8080"
#Reverse proxy 
  reverse-proxy:
    image: reverse-proxy 
    container_name: reverse_proxy
    build:
      context: ./reverse-proxy
    volumes:
      - ./reverse-proxy/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web-app
    ports:
      - "80:80"
#Mysql Docker 
  db:
    image: database
    container_name: database
    build:
      context: ./db
    depends_on:
      - web-app
    ports:
      - "3306:3306"
